name: CollaborativeEditor App CI/CD

on:
  push:
    branches:
      - main      # Trigger action on push to the 'main' branch
  pull_request:
    branches:
      - main      # Trigger action on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest   # Use Ubuntu for the workflow

    steps:
    - name: Check out repository
      uses: actions/checkout@v2   # Check out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'   # Use Node.js version 14 (can be updated)

    - name: Install dependencies
      run: npm install   # Install dependencies

    - name: Run tests
      run: npm test --if-present   # Run tests, if any

    - name: Build React app
      run: npm run build   # Build the React app

    - name: Deploy to GitHub Pages
      if: success()   # Proceed only if previous steps were successful
      run: |
        npm install gh-pages --save-dev  # Install GitHub Pages package
        npm run deploy  # Deploy to GitHub Pages (make sure this is set up)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for deployment
